/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mariogatchi.presenter;

import java.awt.CardLayout;
import java.util.List;
import java.lang.Math;

import mariogatchi.controllers.InputController;
import mariogatchi.use_cases.authentication.AuthenticationPresenter;
import mariogatchi.use_cases.authentication.AuthenticationResponseModel;

/**
 *
 * @author Samuel
 */
public class DisplayPresenter extends javax.swing.JFrame implements AuthenticationPresenter {

    /**
     * Creates new form NewJFrame
     */
    public DisplayPresenter() {
        initComponents();
        initDynamicComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deadDialog = new javax.swing.JDialog();
        deadTxt = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        useItemDialog = new javax.swing.JDialog();
        useItemTxt = new javax.swing.JLabel();
        useItemAcceptBtn = new javax.swing.JButton();
        useItemDeclineBtn = new javax.swing.JButton();
        useItemItemTxt = new javax.swing.JLabel();
        friendCodeDialog = new javax.swing.JDialog();
        friendCodeTxt = new javax.swing.JLabel();
        friendCodeContinueBtn = new javax.swing.JButton();
        friendCodeV = new javax.swing.JLabel();
        errorDialog = new javax.swing.JDialog();
        errorTxt = new javax.swing.JLabel();
        errorContinueBtn = new javax.swing.JButton();
        errorS = new javax.swing.JScrollPane();
        errorF = new javax.swing.JTextArea();
        startScreen = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        titleTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        loginScreen = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameTxt = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JLabel();
        loginScreenTitleTxt = new javax.swing.JLabel();
        loginAcceptBtn = new javax.swing.JButton();
        loginBackBtn = new javax.swing.JButton();
        gameScreen = new javax.swing.JPanel();
        gameLogoutBtn = new javax.swing.JButton();
        gameScreenTitleTxt = new javax.swing.JLabel();
        gameNewBtn = new javax.swing.JButton();
        gameSelectBtn = new javax.swing.JButton();
        homeScreen = new javax.swing.JPanel();
        homeLogoutBtn = new javax.swing.JButton();
        homeScreenTitleTxt = new javax.swing.JLabel();
        homeToParkBtn = new javax.swing.JButton();
        homeToForrestBtn = new javax.swing.JButton();
        homeInventoryBtn = new javax.swing.JButton();
        homeToFriendBtn = new javax.swing.JButton();
        parkScreen = new javax.swing.JPanel();
        parkLogoutBtn = new javax.swing.JButton();
        parkScreenTitleTxt = new javax.swing.JLabel();
        parkToForrestBtn = new javax.swing.JButton();
        parkToHomeBtn = new javax.swing.JButton();
        parkInventoryBtn = new javax.swing.JButton();
        parkToFriendBtn = new javax.swing.JButton();
        forrestScreen = new javax.swing.JPanel();
        forrestLogoutBtn = new javax.swing.JButton();
        forrestScreenTitleTxt = new javax.swing.JLabel();
        forrestAcceptBtn = new javax.swing.JButton();
        forrestNextBtn = new javax.swing.JButton();
        forrestMariogatchiNameTxt = new javax.swing.JLabel();
        forrestViewMariogatchiStatsBtn = new javax.swing.JButton();
        forrestToParkBtn = new javax.swing.JButton();
        forrestToHomeBtn = new javax.swing.JButton();
        forrestInventoryBtn = new javax.swing.JButton();
        forrestToFriendBtn = new javax.swing.JButton();
        mariogatchiScreen = new javax.swing.JPanel();
        mariogatchiBackBtn = new javax.swing.JButton();
        mariogatchiNameTxt = new javax.swing.JLabel();
        mariogatchiHungerVTxt = new javax.swing.JLabel();
        mariogatchiEnergyVTxt = new javax.swing.JLabel();
        mariogatchiCleanlinessVTxt = new javax.swing.JLabel();
        mariogatchiAgilityVTxt = new javax.swing.JLabel();
        mariogatchiStrategyVTxt = new javax.swing.JLabel();
        mariogatchiHungerTxt = new javax.swing.JLabel();
        mariogatchiEnergyTxt = new javax.swing.JLabel();
        mariogatchiCleanlinessTxt = new javax.swing.JLabel();
        mariogatchiAgilityTxt = new javax.swing.JLabel();
        mariogatchiStrategyTxt = new javax.swing.JLabel();
        mariogatchiLastCheckInTxt = new javax.swing.JLabel();
        mariogatchiLastCheckInVTxt = new javax.swing.JLabel();
        mariogatchiRarityVTxt = new javax.swing.JLabel();
        mariogatchiRarityTxt = new javax.swing.JLabel();
        inventoryScreen = new javax.swing.JPanel();
        inventoryBackBtn = new javax.swing.JButton();
        inventoryScreenTitleTxt = new javax.swing.JLabel();
        inventoryItemBadAppleBtn = new javax.swing.JButton();
        inventoryItemLeashBtn = new javax.swing.JButton();
        inventoryItemAppleBtn = new javax.swing.JButton();
        inventoryItemAppleV = new javax.swing.JLabel();
        inventoryItemBadAppleV = new javax.swing.JLabel();
        inventoryItemLeashV = new javax.swing.JLabel();
        friendScreen = new javax.swing.JPanel();
        friendLogoutBtn = new javax.swing.JButton();
        friendScreenTitleTxt = new javax.swing.JLabel();
        friendToForrestBtn = new javax.swing.JButton();
        friendToHomeBtn = new javax.swing.JButton();
        friendInventoryBtn = new javax.swing.JButton();
        friendToParkBtn = new javax.swing.JButton();
        friendFriendCodeBtn = new javax.swing.JButton();

        deadDialog.setFocusableWindowState(false);
        deadDialog.setLocation(new java.awt.Point(0, 0));
        deadDialog.setMinimumSize(new java.awt.Dimension(300, 200));
        deadDialog.setResizable(false);

        deadTxt.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        deadTxt.setText("Ripgatchi");

        continueBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        continueBtn.setText("Continue");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deadDialogLayout = new javax.swing.GroupLayout(deadDialog.getContentPane());
        deadDialog.getContentPane().setLayout(deadDialogLayout);
        deadDialogLayout.setHorizontalGroup(
            deadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deadDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(deadDialogLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deadDialogLayout.setVerticalGroup(
            deadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deadDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(deadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        useItemDialog.setFocusableWindowState(false);
        useItemDialog.setLocation(new java.awt.Point(0, 0));
        useItemDialog.setMinimumSize(new java.awt.Dimension(300, 200));
        useItemDialog.setResizable(false);

        useItemTxt.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        useItemTxt.setText("Use sure you want to use");

        useItemAcceptBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        useItemAcceptBtn.setText("Continue");
        useItemAcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemAcceptBtnActionPerformed(evt);
            }
        });

        useItemDeclineBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        useItemDeclineBtn.setText("Decline");
        useItemDeclineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemDeclineBtnActionPerformed(evt);
            }
        });

        useItemItemTxt.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        useItemItemTxt.setText("null");

        javax.swing.GroupLayout useItemDialogLayout = new javax.swing.GroupLayout(useItemDialog.getContentPane());
        useItemDialog.getContentPane().setLayout(useItemDialogLayout);
        useItemDialogLayout.setHorizontalGroup(
            useItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, useItemDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(useItemItemTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, useItemDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(useItemDeclineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(useItemAcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, useItemDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(useItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        useItemDialogLayout.setVerticalGroup(
            useItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(useItemDialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(useItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(useItemItemTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(useItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useItemAcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useItemDeclineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        friendCodeDialog.setFocusableWindowState(false);
        friendCodeDialog.setLocation(new java.awt.Point(0, 0));
        friendCodeDialog.setMinimumSize(new java.awt.Dimension(300, 200));
        friendCodeDialog.setResizable(false);

        friendCodeTxt.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        friendCodeTxt.setText("Friend Code");

        friendCodeContinueBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendCodeContinueBtn.setText("Continue");
        friendCodeContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendCodeContinueBtnActionPerformed(evt);
            }
        });

        friendCodeV.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendCodeV.setText("null");

        javax.swing.GroupLayout friendCodeDialogLayout = new javax.swing.GroupLayout(friendCodeDialog.getContentPane());
        friendCodeDialog.getContentPane().setLayout(friendCodeDialogLayout);
        friendCodeDialogLayout.setHorizontalGroup(
            friendCodeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, friendCodeDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(friendCodeV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(friendCodeDialogLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(friendCodeContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(friendCodeDialogLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(friendCodeTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        friendCodeDialogLayout.setVerticalGroup(
            friendCodeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendCodeDialogLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(friendCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(friendCodeV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(friendCodeContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        errorDialog.setFocusableWindowState(false);
        errorDialog.setLocation(new java.awt.Point(0, 0));
        errorDialog.setMinimumSize(new java.awt.Dimension(300, 200));
        errorDialog.setResizable(false);

        errorTxt.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        errorTxt.setText("Error");

        errorContinueBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        errorContinueBtn.setText("Continue");
        errorContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorContinueBtnActionPerformed(evt);
            }
        });

        errorF.setColumns(20);
        errorF.setRows(5);
        errorS.setViewportView(errorF);

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(errorContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mariogatchi");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setName("Mariogatchi"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        startScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        startScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        loginBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signupBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        signupBtn.setText("Signup");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        titleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleTxt.setText("Mariogatchi");

        exitBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startScreenLayout = new javax.swing.GroupLayout(startScreen);
        startScreen.setLayout(startScreenLayout);
        startScreenLayout.setHorizontalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startScreenLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        startScreenLayout.setVerticalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleTxt)
                .addGap(84, 84, 84)
                .addGroup(startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        getContentPane().add(startScreen, "Start");

        loginScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        loginScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTxt.setText("Username:");

        passwordTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordTxt.setText("Password:");

        loginScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginScreenTitleTxt.setText("Temp");

        loginAcceptBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        loginAcceptBtn.setText("Login");
        loginAcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAcceptBtnActionPerformed(evt);
            }
        });

        loginBackBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        loginBackBtn.setText("Back");
        loginBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginScreenTitleTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginScreenLayout.createSequentialGroup()
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginScreenLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(passwordTxt))
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginAcceptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(passwordField)))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(loginScreenTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxt)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTxt))
                .addGap(39, 39, 39)
                .addComponent(loginAcceptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(loginBackBtn)
                .addContainerGap())
        );

        getContentPane().add(loginScreen, "Login");

        gameScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        gameScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        gameLogoutBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        gameLogoutBtn.setText("Logout");
        gameLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        gameScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        gameScreenTitleTxt.setText("Choose your game");

        gameNewBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        gameNewBtn.setText("New game");
        gameNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameNewBtnActionPerformed(evt);
            }
        });

        gameSelectBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        gameSelectBtn.setText("Select");
        gameSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameSelectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameScreenLayout = new javax.swing.GroupLayout(gameScreen);
        gameScreen.setLayout(gameScreenLayout);
        gameScreenLayout.setHorizontalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(gameNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(gameSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameScreenTitleTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gameScreenLayout.setVerticalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(gameScreenTitleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameNewBtn)
                    .addComponent(gameSelectBtn))
                .addGap(18, 18, 18)
                .addComponent(gameLogoutBtn)
                .addContainerGap())
        );

        getContentPane().add(gameScreen, "Games");

        homeScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        homeScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        homeLogoutBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        homeLogoutBtn.setText("Logout");
        homeLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        homeScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        homeScreenTitleTxt.setText("Home");

        homeToParkBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        homeToParkBtn.setText("Park");
        homeToParkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toParkBtnActionPerformed(evt);
            }
        });

        homeToForrestBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        homeToForrestBtn.setText("Forrest");
        homeToForrestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toForrestBtnActionPerformed(evt);
            }
        });

        homeInventoryBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        homeInventoryBtn.setText("Inventory");
        homeInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeInventoryBtnActionPerformed(evt);
            }
        });

        homeToFriendBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        homeToFriendBtn.setText("Friend");
        homeToFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFriendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeScreenLayout = new javax.swing.GroupLayout(homeScreen);
        homeScreen.setLayout(homeScreenLayout);
        homeScreenLayout.setHorizontalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(homeScreenLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(homeScreenTitleTxt)
                .addGap(247, 247, 247))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeScreenLayout.createSequentialGroup()
                        .addComponent(homeInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(homeScreenLayout.createSequentialGroup()
                        .addComponent(homeToForrestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeToParkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeToFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        homeScreenLayout.setVerticalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homeScreenTitleTxt)
                .addGap(139, 139, 139)
                .addComponent(homeInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLogoutBtn)
                    .addComponent(homeToForrestBtn)
                    .addComponent(homeToParkBtn)
                    .addComponent(homeToFriendBtn))
                .addContainerGap())
        );

        getContentPane().add(homeScreen, "Home");

        parkScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        parkScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        parkLogoutBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        parkLogoutBtn.setText("Logout");
        parkLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        parkScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        parkScreenTitleTxt.setText("Park");

        parkToForrestBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        parkToForrestBtn.setText("Forrest");
        parkToForrestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toForrestBtnActionPerformed(evt);
            }
        });

        parkToHomeBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        parkToHomeBtn.setText("Home");
        parkToHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomeBtnActionPerformed(evt);
            }
        });

        parkInventoryBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        parkInventoryBtn.setText("Inventory");
        parkInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkInventoryBtnActionPerformed(evt);
            }
        });

        parkToFriendBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        parkToFriendBtn.setText("Friend");
        parkToFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFriendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parkScreenLayout = new javax.swing.GroupLayout(parkScreen);
        parkScreen.setLayout(parkScreenLayout);
        parkScreenLayout.setHorizontalGroup(
            parkScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkScreenLayout.createSequentialGroup()
                .addGroup(parkScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(parkToHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parkToForrestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parkToFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(parkLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(parkScreenLayout.createSequentialGroup()
                        .addGroup(parkScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkScreenLayout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(parkScreenTitleTxt))
                            .addGroup(parkScreenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(parkInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        parkScreenLayout.setVerticalGroup(
            parkScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(parkScreenTitleTxt)
                .addGap(139, 139, 139)
                .addComponent(parkInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(parkScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkLogoutBtn)
                    .addComponent(parkToHomeBtn)
                    .addComponent(parkToForrestBtn)
                    .addComponent(parkToFriendBtn))
                .addContainerGap())
        );

        getContentPane().add(parkScreen, "Park");

        forrestScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        forrestScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        forrestLogoutBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestLogoutBtn.setText("Logout");
        forrestLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        forrestScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        forrestScreenTitleTxt.setText("Forest");

        forrestAcceptBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestAcceptBtn.setText("Accept");
        forrestAcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forrestAcceptBtnActionPerformed(evt);
            }
        });

        forrestNextBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestNextBtn.setText("Next");
        forrestNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forrestNextBtnActionPerformed(evt);
            }
        });

        forrestMariogatchiNameTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestMariogatchiNameTxt.setText("Mariogatchi Name");

        forrestViewMariogatchiStatsBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestViewMariogatchiStatsBtn.setText("View Stats");
        forrestViewMariogatchiStatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forrestViewMariogatchiStatsBtnActionPerformed(evt);
            }
        });

        forrestToParkBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestToParkBtn.setText("Park");
        forrestToParkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toParkBtnActionPerformed(evt);
            }
        });

        forrestToHomeBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestToHomeBtn.setText("Home");
        forrestToHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomeBtnActionPerformed(evt);
            }
        });

        forrestInventoryBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestInventoryBtn.setText("Inventory");
        forrestInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forrestInventoryBtnActionPerformed(evt);
            }
        });

        forrestToFriendBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        forrestToFriendBtn.setText("Friend");
        forrestToFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFriendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forrestScreenLayout = new javax.swing.GroupLayout(forrestScreen);
        forrestScreen.setLayout(forrestScreenLayout);
        forrestScreenLayout.setHorizontalGroup(
            forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forrestScreenLayout.createSequentialGroup()
                .addGroup(forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forrestScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(forrestToHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forrestToParkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forrestToFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(forrestLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forrestScreenLayout.createSequentialGroup()
                        .addGroup(forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(forrestScreenLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(forrestViewMariogatchiStatsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(forrestAcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(forrestNextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(forrestScreenLayout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(forrestMariogatchiNameTxt))
                            .addGroup(forrestScreenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(forrestInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(forrestScreenLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(forrestScreenTitleTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forrestScreenLayout.setVerticalGroup(
            forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forrestScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(forrestScreenTitleTxt)
                .addGap(139, 139, 139)
                .addComponent(forrestInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(forrestMariogatchiNameTxt)
                .addGap(47, 47, 47)
                .addGroup(forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forrestNextBtn)
                    .addComponent(forrestAcceptBtn)
                    .addComponent(forrestViewMariogatchiStatsBtn))
                .addGap(44, 44, 44)
                .addGroup(forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forrestScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(forrestToHomeBtn)
                        .addComponent(forrestToParkBtn)
                        .addComponent(forrestToFriendBtn))
                    .addComponent(forrestLogoutBtn))
                .addContainerGap())
        );

        getContentPane().add(forrestScreen, "Forrest");

        mariogatchiScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        mariogatchiScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        mariogatchiBackBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiBackBtn.setText("Back");
        mariogatchiBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        mariogatchiNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mariogatchiNameTxt.setText("Mariogatchi Name");

        mariogatchiHungerVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiHungerVTxt.setText("0");

        mariogatchiEnergyVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiEnergyVTxt.setText("0");

        mariogatchiCleanlinessVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiCleanlinessVTxt.setText("0");

        mariogatchiAgilityVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiAgilityVTxt.setText("0");

        mariogatchiStrategyVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiStrategyVTxt.setText("0");

        mariogatchiHungerTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiHungerTxt.setText("Hunger:");

        mariogatchiEnergyTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiEnergyTxt.setText("Energy:");

        mariogatchiCleanlinessTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiCleanlinessTxt.setText("Cleanliness:");

        mariogatchiAgilityTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiAgilityTxt.setText("Agility:");

        mariogatchiStrategyTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiStrategyTxt.setText("Strategy:");

        mariogatchiLastCheckInTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiLastCheckInTxt.setText("Last time checked in:");

        mariogatchiLastCheckInVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiLastCheckInVTxt.setText("0");

        mariogatchiRarityVTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiRarityVTxt.setText("null");

        mariogatchiRarityTxt.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        mariogatchiRarityTxt.setText("Rarity:");

        javax.swing.GroupLayout mariogatchiScreenLayout = new javax.swing.GroupLayout(mariogatchiScreen);
        mariogatchiScreen.setLayout(mariogatchiScreenLayout);
        mariogatchiScreenLayout.setHorizontalGroup(
            mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mariogatchiScreenLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(mariogatchiRarityTxt)
                .addGap(18, 18, 18)
                .addComponent(mariogatchiRarityVTxt)
                .addGap(0, 261, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mariogatchiScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mariogatchiScreenLayout.createSequentialGroup()
                        .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mariogatchiScreenLayout.createSequentialGroup()
                                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mariogatchiHungerTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mariogatchiEnergyTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mariogatchiCleanlinessTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mariogatchiAgilityTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mariogatchiLastCheckInTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mariogatchiStrategyTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mariogatchiAgilityVTxt)
                                    .addComponent(mariogatchiCleanlinessVTxt)
                                    .addComponent(mariogatchiEnergyVTxt)
                                    .addComponent(mariogatchiHungerVTxt)
                                    .addComponent(mariogatchiLastCheckInVTxt)
                                    .addComponent(mariogatchiStrategyVTxt)))
                            .addComponent(mariogatchiNameTxt))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mariogatchiScreenLayout.createSequentialGroup()
                        .addComponent(mariogatchiBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        mariogatchiScreenLayout.setVerticalGroup(
            mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mariogatchiScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mariogatchiNameTxt)
                .addGap(34, 34, 34)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiRarityVTxt)
                    .addComponent(mariogatchiRarityTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiHungerVTxt)
                    .addComponent(mariogatchiHungerTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiEnergyVTxt)
                    .addComponent(mariogatchiEnergyTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiCleanlinessVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mariogatchiCleanlinessTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiAgilityVTxt)
                    .addComponent(mariogatchiAgilityTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mariogatchiStrategyTxt)
                    .addComponent(mariogatchiStrategyVTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mariogatchiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mariogatchiLastCheckInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mariogatchiLastCheckInVTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(mariogatchiBackBtn)
                .addContainerGap())
        );

        getContentPane().add(mariogatchiScreen, "Stats");

        inventoryScreen.setMinimumSize(new java.awt.Dimension(600, 500));
        inventoryScreen.setPreferredSize(new java.awt.Dimension(600, 500));

        inventoryBackBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryBackBtn.setText("Back");
        inventoryBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        inventoryScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        inventoryScreenTitleTxt.setText("Inventory");

        inventoryItemBadAppleBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemBadAppleBtn.setText("Bad Apple");
        inventoryItemBadAppleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryItemBadAppleBtnActionPerformed(evt);
            }
        });

        inventoryItemLeashBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemLeashBtn.setText("Leash");
        inventoryItemLeashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryItemLeashBtnActionPerformed(evt);
            }
        });

        inventoryItemAppleBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemAppleBtn.setText("Apple");
        inventoryItemAppleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryItemAppleBtnActionPerformed(evt);
            }
        });

        inventoryItemAppleV.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemAppleV.setText("0");

        inventoryItemBadAppleV.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemBadAppleV.setText("0");

        inventoryItemLeashV.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        inventoryItemLeashV.setText("0");

        javax.swing.GroupLayout inventoryScreenLayout = new javax.swing.GroupLayout(inventoryScreen);
        inventoryScreen.setLayout(inventoryScreenLayout);
        inventoryScreenLayout.setHorizontalGroup(
            inventoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryScreenLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(inventoryScreenTitleTxt)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryScreenLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(inventoryItemAppleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryItemBadAppleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(inventoryItemLeashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(inventoryScreenLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(inventoryItemAppleV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(inventoryItemBadAppleV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(inventoryItemLeashV)
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inventoryScreenLayout.setVerticalGroup(
            inventoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inventoryScreenTitleTxt)
                .addGap(90, 90, 90)
                .addGroup(inventoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryItemBadAppleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryItemLeashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryItemAppleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryItemAppleV)
                    .addComponent(inventoryItemBadAppleV)
                    .addComponent(inventoryItemLeashV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(inventoryBackBtn)
                .addContainerGap())
        );

        getContentPane().add(inventoryScreen, "Inventory");

        friendScreen.setMinimumSize(new java.awt.Dimension(600, 500));

        friendLogoutBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendLogoutBtn.setText("Logout");
        friendLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        friendScreenTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        friendScreenTitleTxt.setText("Friend");

        friendToForrestBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendToForrestBtn.setText("Forrest");
        friendToForrestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toForrestBtnActionPerformed(evt);
            }
        });

        friendToHomeBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendToHomeBtn.setText("Home");
        friendToHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomeBtnActionPerformed(evt);
            }
        });

        friendInventoryBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendInventoryBtn.setText("Inventory");
        friendInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendInventoryBtnActionPerformed(evt);
            }
        });

        friendToParkBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendToParkBtn.setText("Park");
        friendToParkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toParkBtnActionPerformed(evt);
            }
        });

        friendFriendCodeBtn.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        friendFriendCodeBtn.setText("Friend Code");
        friendFriendCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendFriendCodeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout friendScreenLayout = new javax.swing.GroupLayout(friendScreen);
        friendScreen.setLayout(friendScreenLayout);
        friendScreenLayout.setHorizontalGroup(
            friendScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(friendScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendScreenLayout.createSequentialGroup()
                        .addComponent(friendToHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(friendToForrestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(friendToParkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(friendLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(friendScreenLayout.createSequentialGroup()
                        .addComponent(friendInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(friendFriendCodeBtn)))
                .addContainerGap())
            .addGroup(friendScreenLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(friendScreenTitleTxt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        friendScreenLayout.setVerticalGroup(
            friendScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, friendScreenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(friendScreenTitleTxt)
                .addGap(139, 139, 139)
                .addGroup(friendScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friendInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friendFriendCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(friendScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friendLogoutBtn)
                    .addComponent(friendToParkBtn)
                    .addComponent(friendToHomeBtn)
                    .addComponent(friendToForrestBtn))
                .addContainerGap())
        );

        getContentPane().add(friendScreen, "Friend");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initDynamicComponents(){
        inventoryItemLeashV.setVisible(false);
        friendCodeV.setText("i2o3diwfd90ipjondo");
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("hi");
    }//GEN-LAST:event_formWindowClosing

    private void loginAcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAcceptBtnActionPerformed
        InputController.LoginActions la;
        if(isLogin){
            la = InputController.LoginActions.LOGIN;
        }else{
            la = InputController.LoginActions.SIGNUP;
        }
        ic.loginRequest(la, List.of(usernameField.getText(), new String(passwordField.getPassword())));
    }//GEN-LAST:event_loginAcceptBtnActionPerformed

    private void loginBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBackBtnActionPerformed
        changeScreen("Start");
        clearLoginFields();
    }//GEN-LAST:event_loginBackBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Start");
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void forrestNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forrestNextBtnActionPerformed
        updateNewM();
    }//GEN-LAST:event_forrestNextBtnActionPerformed

    private int ran(int scale){
        return (int) Math.random()* scale;
    }
    
    private void updateNewM(){
        if(ran(5) == 0){
            mariogatchiRarityVTxt.setText("Rare");
        }else{
            mariogatchiRarityVTxt.setText("Common");
        }
        mariogatchiCleanlinessVTxt.setText(String.valueOf(ran(30)));
        mariogatchiEnergyVTxt.setText(String.valueOf(ran(30)));
        mariogatchiHungerVTxt.setText(String.valueOf(ran(30)));
        mariogatchiStrategyVTxt.setText(String.valueOf(ran(30)));
        mariogatchiAgilityVTxt.setText(String.valueOf(ran(30)));
    }

    private void forrestAcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forrestAcceptBtnActionPerformed
        changeScreen("Home");
    }//GEN-LAST:event_forrestAcceptBtnActionPerformed

    private void gameNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameNewBtnActionPerformed
        changeScreen("Forrest");
        updateNewM();
    }//GEN-LAST:event_gameNewBtnActionPerformed

    private void forrestViewMariogatchiStatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forrestViewMariogatchiStatsBtnActionPerformed
        changeScreen("Stats");
        updatePreviousScreen("Forrest");
    }//GEN-LAST:event_forrestViewMariogatchiStatsBtnActionPerformed

    private void gameSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameSelectBtnActionPerformed
        changeScreen("Home");
    }//GEN-LAST:event_gameSelectBtnActionPerformed

    private void toParkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toParkBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Park");
            if(ran(2) == 0){
                int temp = ran(1);
                String more = null;
                if(temp == 0){
                    inventoryItemAppleV.setText(String.valueOf(Integer.parseInt(inventoryItemAppleV.getText()) + 1));
                    more = "Apple";
                }else{
                    inventoryItemBadAppleV.setText(String.valueOf(Integer.parseInt(inventoryItemBadAppleV.getText()) + 1));
                    more = "Bad Apple";
                }
                errorTxt.setText("");
                errorF.setText("You got 1 " + more);
                errorDialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_toParkBtnActionPerformed

    private void toForrestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toForrestBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Forrest");
            updateNewM();
        }
    }//GEN-LAST:event_toForrestBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen(previousScreen);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        changeScreen("Login");
        loginScreenTitleTxt.setText("Signup for an account");
    }//GEN-LAST:event_signupBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        changeScreen("Login");
        loginScreenTitleTxt.setText("Login into an account");
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitBtnActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        deadDialog.setVisible(false);
    }//GEN-LAST:event_continueBtnActionPerformed

    private void toHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHomeBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Home");
        }
    }//GEN-LAST:event_toHomeBtnActionPerformed

    private void useItemAcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemAcceptBtnActionPerformed
        useItemDialog.setVisible(false);
        remove1();
    }//GEN-LAST:event_useItemAcceptBtnActionPerformed

    private void remove1(){
        if(useItemItemTxt.getText() == "Apple"){
            inventoryItemAppleV.setText(String.valueOf(Integer.parseInt(inventoryItemAppleV.getText()) - 1));
        }else if(useItemTxt.getText() == "Bad Apple"){
            inventoryItemBadAppleV.setText(String.valueOf(Integer.parseInt(inventoryItemBadAppleV.getText()) - 1));
        }
    }

    private void useItemDeclineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemDeclineBtnActionPerformed
        useItemDialog.setVisible(false);
    }//GEN-LAST:event_useItemDeclineBtnActionPerformed

    private void inventoryItemAppleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryItemAppleBtnActionPerformed
        if(!isDialogOpen() && Integer.parseInt(inventoryItemAppleV.getText()) > 0){
            useItem("Apple");
        }
    }//GEN-LAST:event_inventoryItemAppleBtnActionPerformed

    private void inventoryItemBadAppleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryItemBadAppleBtnActionPerformed
        if(!isDialogOpen() && Integer.parseInt(inventoryItemBadAppleV.getText()) > 0){
            useItem("Bad Apple");
        }
    }//GEN-LAST:event_inventoryItemBadAppleBtnActionPerformed

    private void inventoryItemLeashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryItemLeashBtnActionPerformed
        if(!isDialogOpen()){
            useItem("Leash");
        }
    }//GEN-LAST:event_inventoryItemLeashBtnActionPerformed

    private void toFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFriendBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Friend");
        }
    }//GEN-LAST:event_toFriendBtnActionPerformed

    private void homeInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeInventoryBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Inventory");
            updatePreviousScreen("Home");
        }
    }//GEN-LAST:event_homeInventoryBtnActionPerformed

    private void parkInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkInventoryBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Inventory");
            updatePreviousScreen("Park");
        }
    }//GEN-LAST:event_parkInventoryBtnActionPerformed

    private void forrestInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forrestInventoryBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Inventory");
            updatePreviousScreen("Forrest");
        }
    }//GEN-LAST:event_forrestInventoryBtnActionPerformed

    private void friendInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendInventoryBtnActionPerformed
        if(!isDialogOpen()){
            changeScreen("Inventory");
            updatePreviousScreen("Friend");
        }
    }//GEN-LAST:event_friendInventoryBtnActionPerformed

    private void friendFriendCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendFriendCodeBtnActionPerformed
        friendCodeDialog.setVisible(true);
    }//GEN-LAST:event_friendFriendCodeBtnActionPerformed

    private void friendCodeContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendCodeContinueBtnActionPerformed
        friendCodeDialog.setVisible(false);
    }//GEN-LAST:event_friendCodeContinueBtnActionPerformed

    private void errorContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorContinueBtnActionPerformed
        errorDialog.setVisible(false);
    }//GEN-LAST:event_errorContinueBtnActionPerformed
    
    private String previousScreen = "Start";
    
    private void changeScreen(String screenName){
        ((CardLayout) getContentPane().getLayout()).show(getContentPane(), screenName);
    }
    
    private void updatePreviousScreen(String screenName){
        previousScreen = screenName;
    }
    
    private void clearLoginFields(){
        usernameField.setText("");
        passwordField.setText("");
    }
    
    private void useItem(String itemName){
        useItemItemTxt.setText(itemName);
        useItemDialog.setVisible(true);
    }
    
    private Boolean isDialogOpen(){
        return friendCodeDialog.isVisible() || deadDialog.isVisible() || useItemDialog.isVisible() || errorDialog.isVisible();
    }

    private Boolean isLogin = false;
    private InputController ic;

    @Override
    public AuthenticationResponseModel prepareLoginSuccess(AuthenticationResponseModel responseModel){
        changeScreen("Games");
        clearLoginFields();
        return responseModel;
    }

    @Override
    public AuthenticationResponseModel prepareLoginFailure(AuthenticationResponseModel responseModel){
        errorDialog.setVisible(true);
        errorTxt.setText("Error");
        errorF.setText("Invalid credentials");
        return responseModel;
    }
    
    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(DisplayPresenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(DisplayPresenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(DisplayPresenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(DisplayPresenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new DisplayPresenter().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueBtn;
    private javax.swing.JDialog deadDialog;
    private javax.swing.JLabel deadTxt;
    private javax.swing.JButton errorContinueBtn;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JTextArea errorF;
    private javax.swing.JScrollPane errorS;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton forrestAcceptBtn;
    private javax.swing.JButton forrestInventoryBtn;
    private javax.swing.JButton forrestLogoutBtn;
    private javax.swing.JLabel forrestMariogatchiNameTxt;
    private javax.swing.JButton forrestNextBtn;
    private javax.swing.JPanel forrestScreen;
    private javax.swing.JLabel forrestScreenTitleTxt;
    private javax.swing.JButton forrestToFriendBtn;
    private javax.swing.JButton forrestToHomeBtn;
    private javax.swing.JButton forrestToParkBtn;
    private javax.swing.JButton forrestViewMariogatchiStatsBtn;
    private javax.swing.JButton friendCodeContinueBtn;
    private javax.swing.JDialog friendCodeDialog;
    private javax.swing.JLabel friendCodeTxt;
    private javax.swing.JLabel friendCodeV;
    private javax.swing.JButton friendFriendCodeBtn;
    private javax.swing.JButton friendInventoryBtn;
    private javax.swing.JButton friendLogoutBtn;
    private javax.swing.JPanel friendScreen;
    private javax.swing.JLabel friendScreenTitleTxt;
    private javax.swing.JButton friendToForrestBtn;
    private javax.swing.JButton friendToHomeBtn;
    private javax.swing.JButton friendToParkBtn;
    private javax.swing.JButton gameLogoutBtn;
    private javax.swing.JButton gameNewBtn;
    private javax.swing.JPanel gameScreen;
    private javax.swing.JLabel gameScreenTitleTxt;
    private javax.swing.JButton gameSelectBtn;
    private javax.swing.JButton homeInventoryBtn;
    private javax.swing.JButton homeLogoutBtn;
    private javax.swing.JPanel homeScreen;
    private javax.swing.JLabel homeScreenTitleTxt;
    private javax.swing.JButton homeToForrestBtn;
    private javax.swing.JButton homeToFriendBtn;
    private javax.swing.JButton homeToParkBtn;
    private javax.swing.JButton inventoryBackBtn;
    private javax.swing.JButton inventoryItemAppleBtn;
    private javax.swing.JLabel inventoryItemAppleV;
    private javax.swing.JButton inventoryItemBadAppleBtn;
    private javax.swing.JLabel inventoryItemBadAppleV;
    private javax.swing.JButton inventoryItemLeashBtn;
    private javax.swing.JLabel inventoryItemLeashV;
    private javax.swing.JPanel inventoryScreen;
    private javax.swing.JLabel inventoryScreenTitleTxt;
    private javax.swing.JButton loginAcceptBtn;
    private javax.swing.JButton loginBackBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JLabel loginScreenTitleTxt;
    private javax.swing.JLabel mariogatchiAgilityTxt;
    private javax.swing.JLabel mariogatchiAgilityVTxt;
    private javax.swing.JButton mariogatchiBackBtn;
    private javax.swing.JLabel mariogatchiCleanlinessTxt;
    private javax.swing.JLabel mariogatchiCleanlinessVTxt;
    private javax.swing.JLabel mariogatchiEnergyTxt;
    private javax.swing.JLabel mariogatchiEnergyVTxt;
    private javax.swing.JLabel mariogatchiHungerTxt;
    private javax.swing.JLabel mariogatchiHungerVTxt;
    private javax.swing.JLabel mariogatchiLastCheckInTxt;
    private javax.swing.JLabel mariogatchiLastCheckInVTxt;
    private javax.swing.JLabel mariogatchiNameTxt;
    private javax.swing.JLabel mariogatchiRarityTxt;
    private javax.swing.JLabel mariogatchiRarityVTxt;
    private javax.swing.JPanel mariogatchiScreen;
    private javax.swing.JLabel mariogatchiStrategyTxt;
    private javax.swing.JLabel mariogatchiStrategyVTxt;
    private javax.swing.JButton parkInventoryBtn;
    private javax.swing.JButton parkLogoutBtn;
    private javax.swing.JPanel parkScreen;
    private javax.swing.JLabel parkScreenTitleTxt;
    private javax.swing.JButton parkToForrestBtn;
    private javax.swing.JButton parkToFriendBtn;
    private javax.swing.JButton parkToHomeBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordTxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JPanel startScreen;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JButton useItemAcceptBtn;
    private javax.swing.JButton useItemDeclineBtn;
    private javax.swing.JDialog useItemDialog;
    private javax.swing.JLabel useItemItemTxt;
    private javax.swing.JLabel useItemTxt;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
